---
apiVersion: v1
kind: Pod
metadata:
  name: jumppod
spec:
  containers:
    - name: jumppod
      image: ghcr.io/twplatformlabs/jumppod:stable
      command: ["sleep", "3600"]
      imagePullPolicy: Always
